import nextConfig from 'eslint-config-next'
import nextTypescript from 'eslint-config-next/typescript'

/**
 * Flat ESLint config.
 *
 * `eslint-config-next` exports an array of flat-config objects (not a factory), so it is
 * spread rather than called.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'contracts/lib/**',
      'contracts/out/**',
      'contracts/cache/**',
      'public/**',
      'src/abi/**', // generated by scripts/export-abis.ts
    ],
  },
  ...nextConfig,
  ...nextTypescript,
  {
    // Pinned explicitly: eslint-plugin-react's auto-detection uses an older ESLint context
    // API and throws under ESLint 10. Declaring the version skips detection entirely.
    settings: {react: {version: '19.3'}},
    rules: {
      // Diagnostic logging has no place in shipped UI; warn/error are allowed for genuine
      // failures that an operator needs to see.
      'no-console': ['warn', {allow: ['warn', 'error']}],
      '@typescript-eslint/no-explicit-any': 'error',
      eqeqeq: ['error', 'always', {null: 'ignore'}],
    },
  },
]

export default config
