import verified from '../../scripts/data/arc-token-verified.json'
import logoManifest from '../../public/tokens/logo-manifest.json'

/**
 * The Arcade reward registry.
 *
 * ## Where this data comes from
 *
 * Every address here was verified against Arc Mainnet by `scripts/verify-arc-tokens.ts`,
 * which reads `name`/`symbol`/`decimals`/`totalSupply` straight from the contract and then
 * executes `transfer` against live state through an `eth_call` state override to confirm the
 * full amount actually arrives. Tokens that fail any check are recorded with their reasons
 * and never reach this file.
 *
 * No address in Arcade is hand-written. If a token is not in the verification report, it
 * cannot be a reward.
 *
 * ## Why nothing here is a "top token" ranking
 *
 * Arc mainnet opened on 2026-09-16. Rankings will churn for months. This module exposes a
 * *configurable registry* — enable, disable, pause, re-tier, set inventory — and the
 * ordering you see in the UI comes from live registry state onchain, not from a list baked
 * into the bundle. The seeds below exist so a fresh checkout has something coherent to show.
 *
 * ## What "Verified by Arcade" means
 *
 * That we checked the token *contract*: right address, honest decimals, transfers that do
 * not skim. It is not a judgement about the asset, its price, or its prospects, and it is
 * not an endorsement by anyone.
 */

export type RewardTier = 'featured' | 'verified' | 'discovery' | 'paused'

export type RewardAsset = {
  address: `0x${string}`
  symbol: string
  name: string
  decimals: number
  tier: RewardTier
  /** True only when the live transfer probe moved the full amount and returned true. */
  transferVerified: boolean
  /** Point-in-time third-party snapshot. Never used for solvency maths. */
  snapshot: {
    liquidityUsd: number
    volume24hUsd: number
    holders: number
    ageDays: number
    source: string
    capturedAt: string
  }
  /** The project's real published logo. Absent when none exists; never generated by us. */
  logoUri?: string
  /** When there is no logo, why — so a monogram reads as a finding, not an oversight. */
  logoNote?: string
  /** Short editorial note shown in the reward drawer. */
  note?: string
}

type VerifiedToken = (typeof verified)['tokens'][number]

/**
 * Real published logos, keyed by contract address.
 *
 * Built by `scripts/fetch-token-logos.ts`, which downloads each project's actual mark and
 * records where it came from. A token with no published logo is deliberately absent here and
 * falls back to a typographic monogram — Arcade never draws or approximates someone else's
 * logo, because on a chain with six ticker collisions a plausible fake mark is a direct route
 * to confusing two different assets.
 *
 * Keyed by address, never by ticker, for the same reason.
 */
const LOGO_BY_ADDRESS: Record<string, string> = Object.fromEntries(
  logoManifest.logos
    .filter((entry): entry is typeof entry & {file: string} => typeof entry.file === 'string')
    .map((entry) => [entry.address.toLowerCase(), `/tokens/${entry.file}`]),
)

/** Why a given token shows a monogram instead of a logo, for the reward drawer. */
const LOGO_NOTE_BY_ADDRESS: Record<string, string> = Object.fromEntries(
  logoManifest.logos
    .filter((entry) => entry.file === null && typeof entry.note === 'string')
    .map((entry) => [entry.address.toLowerCase(), entry.note as string]),
)

export const LOGO_SUMMARY = logoManifest.summary

/**
 * Curation assigned by Arcade. Keyed by address, never by ticker — research found six
 * ticker collisions among Arc candidates, including two tokens squatting "USDC".
 */
const CURATION: Record<string, {tier: RewardTier; note?: string}> = {
  '0xece5ca8bf9220718e5727754026757512212cb3c': {
    tier: 'featured',
    note: 'Highest 24h volume of any asset in the reward set at the time of verification.',
  },
  '0xbc43ce8dec648ea298c4275559b81d6261c90b67': {tier: 'featured'},
  '0x171a4217b86a807a64eb94757db6849fb4bdbaa0': {
    tier: 'featured',
    note: 'Deepest liquidity in the reward set. Eight decimals — reward bands are small by design.',
  },
  '0x2ba0f44bdfc17fba30eda9cdbecb908ca45b043b': {tier: 'featured'},
  '0xeb64987643db71c76b2a2be7e723decc995e5b37': {tier: 'verified'},
  '0x07704b06981ea962b87296362a1281484d160000': {tier: 'verified'},
  '0x2164bb17a2d38c1b5170e987b2c0416df1efc752': {tier: 'verified'},
  '0x128cc466b61f542da60c70e3aa11c10e19b84edb': {tier: 'verified'},
  '0xbef5f6d51cb62b58e6a8f77868681825c6fe21c1': {
    tier: 'verified',
    note: 'Circle-issued EURC. Address taken from official Arc documentation. Six decimals.',
  },
  '0x8c4252c87081c88c6ad57d6dd97e1cafebf842b7': {tier: 'verified'},
  '0x1ea1e4f9a9975f1f6e9c0a9f6e8ada7a66e6de52': {tier: 'discovery'},
  '0x12ce1f970722ca6e08364b60099b3d25c09b5434': {
    tier: 'discovery',
    note: 'Four days old at verification. Sits in Discovery for that reason alone.',
  },
  '0xbe0cad585ea2d13de2f4e36376be755c0afd8b97': {tier: 'discovery'},
}

function toRewardAsset(token: VerifiedToken): RewardAsset | null {
  const {onchain, marketSnapshot, transferBehaviour} = token
  if (!onchain.symbol || !onchain.name || onchain.decimals === null) return null

  const curation = CURATION[token.address] ?? {tier: 'discovery' as RewardTier}
  const logoUri = LOGO_BY_ADDRESS[token.address]
  const logoNote = LOGO_NOTE_BY_ADDRESS[token.address]

  return {
    address: token.address as `0x${string}`,
    symbol: onchain.symbol,
    name: onchain.name,
    decimals: onchain.decimals,
    tier: curation.tier,
    transferVerified: transferBehaviour.callSucceeded === true && transferBehaviour.feeBps === 0,
    snapshot: {
      liquidityUsd: marketSnapshot.liquidityUsd,
      volume24hUsd: marketSnapshot.volume24hUsd,
      holders: marketSnapshot.holders,
      ageDays: marketSnapshot.ageDays,
      source: marketSnapshot.source,
      capturedAt: marketSnapshot.capturedAt,
    },
    ...(logoUri ? {logoUri} : {}),
    ...(logoNote ? {logoNote} : {}),
    ...(curation.note ? {note: curation.note} : {}),
  }
}

/** Assets that passed every verification check, ready to be configured onto machines. */
export const REWARD_ASSETS: RewardAsset[] = verified.tokens
  .filter((t) => t.eligible)
  .map(toRewardAsset)
  .filter((a): a is RewardAsset => a !== null)

/**
 * Candidates that were checked and rejected, with the reasons. Published on /rewards
 * because showing what we turned away says more about the filter than a list of winners.
 */
export const REJECTED_CANDIDATES = verified.tokens
  .filter((t) => !t.eligible)
  .map((t) => ({
    address: t.address as `0x${string}`,
    symbol: t.onchain.symbol,
    name: t.onchain.name,
    reasons: t.failureReasons,
    tickerCollision: t.tickerCollision,
    transferNote: t.transferBehaviour.note,
    researchFlag: 'researchFlag' in t ? (t.researchFlag as string) : undefined,
  }))

export const VERIFICATION_META = {
  generatedAt: verified.generatedAt,
  chainId: verified.chainId,
  verifiedAtBlock: verified.verifiedAtBlock,
  thresholds: verified.eligibilityThresholds,
  summary: verified.summary,
  sources: verified.sources,
  canonicalUsdc: verified.canonicalUsdc,
} as const

export function assetByAddress(address: string): RewardAsset | undefined {
  const lower = address.toLowerCase()
  return REWARD_ASSETS.find((a) => a.address.toLowerCase() === lower)
}

export function assetsByTier(tier: RewardTier): RewardAsset[] {
  return REWARD_ASSETS.filter((a) => a.tier === tier)
}

export const TIER_LABEL: Record<RewardTier, string> = {
  featured: 'Featured',
  verified: 'Verified by Arcade',
  discovery: 'Discovery',
  paused: 'Paused',
}

export const TIER_MEANING: Record<RewardTier, string> = {
  featured: 'Verified, and currently highlighted on a machine.',
  verified: 'Arcade confirmed the contract address, decimals and transfer behaviour.',
  discovery: 'Verified, but newer or thinner. Held to the same contract checks, higher risk.',
  paused: 'Temporarily withheld from machines. Existing rewards remain claimable.',
}
