import verified from '../../scripts/data/arc-token-verified.json'
import logoManifest from '../../public/tokens/logo-manifest.json'

/**
 * The Arcade reward registry.
 *
 * ## Where this data comes from
 *
 * Every address here was verified against Arc Mainnet by `scripts/verify-arc-tokens.ts`,
 * which reads `name`/`symbol`/`decimals`/`totalSupply` straight from the contract and then
 * executes `transfer` against live state through an `eth_call` state override to confirm the
 * full amount actually arrives. Tokens that fail any check are recorded with their reasons
 * and never reach this file.
 *
 * No address in Arcade is hand-written. If a token is not in the verification report, it
 * cannot be a reward.
 *
 * ## Why nothing here is a "top token" ranking
 *
 * Arc mainnet opened on 2026-09-16. Rankings will churn for months. This module exposes a
 * *configurable registry* — enable, disable, pause, re-tier, set inventory — and the
 * ordering you see in the UI comes from live registry state onchain, not from a list baked
 * into the bundle. The seeds below exist so a fresh checkout has something coherent to show.
 *
 * ## What "Verified by Arcade" means
 *
 * That we checked the token *contract*: right address, honest decimals, transfers that do
 * not skim. It is not a judgement about the asset, its price, or its prospects, and it is
 * not an endorsement by anyone.
 */

export type RewardTier = 'featured' | 'verified' | 'discovery' | 'paused'

export type RewardAsset = {
  address: `0x${string}`
  /** The symbol the contract reports. The registry asserts this on-chain; never override it. */
  symbol: string
  /**
   * What players are shown instead of {@link symbol}, when the real ticker would mislead.
   *
   * Only set for admitted ticker collisions — see {@link ADMITTED_COLLISIONS}. Everywhere a
   * reward is displayed, use {@link labelFor} rather than `symbol`.
   */
  displaySymbol?: string
  /** Why this asset carries a display override, shown next to it in the UI. */
  collisionNote?: string
  name: string
  decimals: number
  tier: RewardTier
  /** True only when the live transfer probe moved the full amount and returned true. */
  transferVerified: boolean
  /** Point-in-time third-party snapshot. Never used for solvency maths. */
  snapshot: {
    liquidityUsd: number
    volume24hUsd: number
    holders: number
    ageDays: number
    source: string
    capturedAt: string
  }
  /** The project's real published logo. Absent when none exists; never generated by us. */
  logoUri?: string
  /** When there is no logo, why — so a monogram reads as a finding, not an oversight. */
  logoNote?: string
  /** Short editorial note shown in the reward drawer. */
  note?: string
}

type VerifiedToken = (typeof verified)['tokens'][number]

/**
 * Real published logos, keyed by contract address.
 *
 * Built by `scripts/fetch-token-logos.ts`, which downloads each project's actual mark and
 * records where it came from. A token with no published logo is deliberately absent here and
 * falls back to a typographic monogram — Arcade never draws or approximates someone else's
 * logo, because on a chain with six ticker collisions a plausible fake mark is a direct route
 * to confusing two different assets.
 *
 * Keyed by address, never by ticker, for the same reason.
 */
const LOGO_BY_ADDRESS: Record<string, string> = Object.fromEntries(
  logoManifest.logos
    .filter((entry): entry is typeof entry & {file: string} => typeof entry.file === 'string')
    .map((entry) => [entry.address.toLowerCase(), `/tokens/${entry.file}`]),
)

/** Why a given token shows a monogram instead of a logo, for the reward drawer. */
const LOGO_NOTE_BY_ADDRESS: Record<string, string> = Object.fromEntries(
  logoManifest.logos
    .filter((entry) => entry.file === null && typeof entry.note === 'string')
    .map((entry) => [entry.address.toLowerCase(), entry.note as string]),
)

export const LOGO_SUMMARY = logoManifest.summary

/**
 * Curation assigned by Arcade. Keyed by address, never by ticker — research found six
 * ticker collisions among Arc candidates, including two tokens squatting "USDC".
 */
const CURATION: Record<string, {tier: RewardTier; note?: string}> = {
  '0xece5ca8bf9220718e5727754026757512212cb3c': {
    tier: 'featured',
    note: 'Highest 24h volume of any asset in the reward set at the time of verification.',
  },
  '0xbc43ce8dec648ea298c4275559b81d6261c90b67': {tier: 'featured'},
  '0x171a4217b86a807a64eb94757db6849fb4bdbaa0': {
    tier: 'featured',
    note: 'Deepest liquidity in the reward set. Eight decimals — reward bands are small by design.',
  },
  '0x2ba0f44bdfc17fba30eda9cdbecb908ca45b043b': {tier: 'featured'},
  '0xeb64987643db71c76b2a2be7e723decc995e5b37': {tier: 'verified'},
  '0x07704b06981ea962b87296362a1281484d160000': {tier: 'verified'},
  '0x2164bb17a2d38c1b5170e987b2c0416df1efc752': {tier: 'verified'},
  '0x128cc466b61f542da60c70e3aa11c10e19b84edb': {tier: 'verified'},
  '0xbef5f6d51cb62b58e6a8f77868681825c6fe21c1': {
    tier: 'verified',
    note: 'Circle-issued EURC. Address taken from official Arc documentation. Six decimals.',
  },
  '0x8c4252c87081c88c6ad57d6dd97e1cafebf842b7': {tier: 'verified'},
  '0x1ea1e4f9a9975f1f6e9c0a9f6e8ada7a66e6de52': {tier: 'discovery'},
  '0x12ce1f970722ca6e08364b60099b3d25c09b5434': {
    tier: 'discovery',
    note: 'Four days old at verification. Sits in Discovery for that reason alone.',
  },
  '0xbe0cad585ea2d13de2f4e36376be755c0afd8b97': {tier: 'discovery'},
}

function toRewardAsset(token: VerifiedToken): RewardAsset | null {
  const {onchain, marketSnapshot, transferBehaviour} = token
  if (!onchain.symbol || !onchain.name || onchain.decimals === null) return null

  const curation = CURATION[token.address] ?? {tier: 'discovery' as RewardTier}
  const logoUri = LOGO_BY_ADDRESS[token.address]
  const logoNote = LOGO_NOTE_BY_ADDRESS[token.address]

  return {
    address: token.address as `0x${string}`,
    symbol: onchain.symbol,
    name: onchain.name,
    decimals: onchain.decimals,
    tier: curation.tier,
    transferVerified: transferBehaviour.callSucceeded === true && transferBehaviour.feeBps === 0,
    snapshot: {
      liquidityUsd: marketSnapshot.liquidityUsd,
      volume24hUsd: marketSnapshot.volume24hUsd,
      holders: marketSnapshot.holders,
      ageDays: marketSnapshot.ageDays,
      source: marketSnapshot.source,
      capturedAt: marketSnapshot.capturedAt,
    },
    ...(ADMITTED_COLLISIONS[token.address.toLowerCase()]
      ? {
          displaySymbol: ADMITTED_COLLISIONS[token.address.toLowerCase()]!.displaySymbol,
          collisionNote: ADMITTED_COLLISIONS[token.address.toLowerCase()]!.reason,
        }
      : {}),
    ...(logoUri ? {logoUri} : {}),
    ...(logoNote ? {logoNote} : {}),
    ...(curation.note ? {note: curation.note} : {}),
  }
}

/** Assets that passed every verification check, ready to be configured onto machines. */
/**
 * Tokens admitted despite `eligible: false`, each with the reason and a safe display label.
 *
 * Every entry here is published on /rewards as an admission, with the checks it failed. An
 * operator may decide a token is worth paying out anyway; what is not acceptable is a page
 * that advertises thresholds while quietly paying something that fails them.
 *
 * ## The rule
 *
 * An admission can only ever waive *market* findings — ticker collision, age, or a research
 * flag. It can never waive a contract-level finding. A token whose `transfer()` took a fee,
 * returned a non-standard value, or could not be probed at all stays rejected no matter what
 * is written here; {@link admissible} enforces that, so this list cannot be used to smuggle a
 * broken token into a reward table.
 *
 * ## Why a ticker collision is displayable rather than disqualifying
 *
 * A collision is a labelling problem, not a contract problem. The machine pays a specific
 * address, and the contract never reads a ticker. The only real risk is a player misreading
 * what they won — so the fix is to stop showing the misleading string, which is what
 * `displaySymbol` does. The true symbol is still registered on-chain and still shown on
 * /rewards next to the collision warning.
 */
const ADMITTED_COLLISIONS: Record<
  string,
  {displaySymbol?: string; reason: string; disclose?: string}
> = {
  // Real token, real liquidity, transfer-probed clean. Its ticker is USDC, which on a screen
  // that also says "you paid 2 USDC" would read as the stablecoin. Shown as UDCAT instead.
  '0x8e98a62a995a50eca9979bfa016f91bf36a8f9d9': {
    displaySymbol: 'UDCAT',
    reason: 'Ticker is USDC but this is UpSideDownCat, not Circle USDC. Displayed as UDCAT.',
    disclose: 'Admitted despite a ticker collision with USDC. Shown as UDCAT so a reward is never labelled as the stablecoin.',
  },
  /*
   * $ARCADE, this project's own token, added at the operator's direction.
   *
   * It passes every contract-level check: transfer probed against live mainnet state moved
   * the full amount, zero fee, standard bool return, real supply. It fails the market
   * thresholds — liquidity roughly 7x short, 24h volume far short, and it is days old.
   *
   * That matters for a player: at this depth a large win cannot be sold at anything near the
   * quoted price. Publishing the admission and its reasons is the condition for paying it
   * out at all, so /rewards shows this alongside the thresholds rather than in place of them.
   */
  '0x1ec721ce66eb56c1db87962e7e4fc8d0e3ef24b6': {
    reason: "The project's own token, admitted by the operator despite failing market depth.",
    disclose:
      'Admitted by the operator despite failing the liquidity, volume and age thresholds. It passes every contract check, but the pool is thin — a large win may not be sellable near the quoted price.',
  },
  /*
   * REGI and AKIT, added at the operator's direction.
   *
   * Both clear every contract-level check — transfer probed against live mainnet state moved
   * the full amount, zero fee, standard bool return, 18 decimals, real supply. Both fail on
   * market depth: liquidity is below the published floor (REGI ~$38k, AKIT ~$41k against a
   * $50k bar), and neither has a measured holder count, which is recorded as zero rather than
   * estimated and so fails that check too.
   *
   * Volume and age both pass, which is the difference between these and $ARCADE: they trade,
   * they are just thin. A large win still moves the price against whoever won it, and saying
   * so is the condition for paying them out.
   */
  '0x93d5b8c53ee763c2c4522bf0d958ce51af4360ae': {
    reason: 'Admitted by the operator despite liquidity below the published floor.',
    disclose:
      'Admitted despite failing the liquidity and holder-count thresholds. It passes every contract check and trades actively, but the pool is shallow — a large win may not be sellable near the quoted price.',
  },
  '0xbc3764348131fe1962f267f442a8fe30459ededd': {
    reason: 'Admitted by the operator despite liquidity below the published floor.',
    disclose:
      'Admitted despite failing the liquidity and holder-count thresholds. It passes every contract check and trades actively, but the pool is shallow — a large win may not be sellable near the quoted price.',
  },
  /*
   * Synthra sStocks, admitted at the operator's direction.
   *
   * Tokenised equity exposure bridged from Robinhood Chain to Arc over LayerZero, backed by
   * stock tokens locked on the source chain. Unlike every other tokenised-equity product
   * checked for this project, these are permissionless ERC-20s: sNVDA's transfer was probed
   * against live mainnet state and moved the full amount, returning true. That is what makes
   * them payable as a prize at all — a whitelisted security token reverts when the winner is
   * whoever happened to spin.
   *
   * Two things a player is owed here, and neither is waivable by listing them below.
   *
   * The contract-level checks still gate entry. Most of these have no bridged supply yet, so
   * no holder exists to probe, and `contractChecksPass` keeps them out until one does — an
   * admission cannot vouch for a transfer nobody has observed.
   *
   * And Synthra's own documentation calls this a pre-audit release. A reward that depends on
   * a bridge's backing is exposed to that bridge, which is a different risk from a token that
   * simply trades thinly, so the disclosure says so rather than reusing the liquidity wording.
   */
  '0x5b7fd6e1dd3b1b47888252cad8eef3ae2b4fc6d7': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised NVDA exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0x22afca741bba52d1f11f6d10fdf636a4d721458e': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised META exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0x74a7456575fb29035077b42c5b2813ca98052358': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised PLTR exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0x549288985bfafb9d869f1190615099ebef7a7838': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised GOOGL exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0x4abee9e7606e24f1c0e047f315c4189a16bf1eb6': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised AAPL exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0xc5a6e295c1f1a889e92067c81432e8b83cffff81': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised MSFT exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0x0dfa611e17c9df6ccacc50f2d444d9518df00942': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised INTC exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0x4f4b12590e5f4f85a98e630a133761f324044499': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised AMZN exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0x2f212f3372a83bf9dbeeb5b47bde519e18b80d85': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised AMD exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0xfb7dd9f2f7e4fbac3519601c23db3d65523aa7f0': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised TSLA exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0xbe4d721ea71ae69d7f0c1d119d58899db6b22347': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised COIN exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  '0xf8108d3c5f6df74bc4e7aaeed430dc1e53ecde37': {
    reason: 'Synthra sStock, bridged equity exposure admitted by the operator.',
    disclose:
      'Tokenised AVGO exposure bridged to Arc by Synthra and backed by stock tokens locked on Robinhood Chain — not a direct holding, and redeemable only through that bridge. Synthra describe it as a pre-audit release. Thin or absent Arc liquidity means a win may not be sellable near the quoted price.',
  },
  /*
   * Builders, added at the operator's direction.
   *
   * Clears every contract-level check: transfer probed against live mainnet state moved the
   * full amount, zero fee, standard bool return, 18 decimals, no ticker collision. It is also
   * the oldest admission here by a distance — roughly two months, where the others were days.
   *
   * It is admitted on thinner market data than REGI or AKIT, which both cleared the volume
   * threshold. This one clears neither: liquidity is about a third of the floor and 24h volume
   * roughly a fifteenth of it. At that depth a winner selling a whole prize is a visible
   * fraction of a day's trade, so the disclosure says volume explicitly rather than hiding it
   * behind the general liquidity wording.
   */
  '0xa37c1f9b2483b3b45ced74b10e19223aa76d18f2': {
    reason: 'Admitted by the operator despite failing both liquidity and volume thresholds.',
    disclose:
      'Admitted despite failing the liquidity, volume and holder-count thresholds. It passes every contract check, but both the pool and daily volume are thin — selling a full win may move the price against you.',
  },
  /*
   * TIDE, added at the operator's direction.
   *
   * Clears every contract-level check — transfer probed against live mainnet state moved the
   * full amount, zero fee, standard bool return, 18 decimals, no ticker collision — and clears
   * the liquidity floor comfortably at roughly $83k. Volume is what it fails, at about a third
   * of the threshold.
   *
   * It is also the only reward here that trades on a single venue. There is no Uniswap pool
   * for it at any fee tier; it exists on Arc's own AMM and nowhere else. That matters to a
   * winner in a way the liquidity number alone does not say: selling means using that one
   * market, so the disclosure names it rather than leaving the reader to discover it.
   */
  '0x92395d0cd51bb504a39e53105cb6862948af1b8e': {
    reason: 'Admitted by the operator despite volume below the published floor.',
    disclose:
      'Admitted despite failing the volume and holder-count thresholds. It passes every contract check and the pool is reasonably deep, but it trades on one venue only — Arc’s own AMM — so selling a win means using that single market.',
  },
  /*
   * KAIRO, admitted at the operator's direction.
   *
   * Clears every contract-level check — transfer probed against live mainnet state, full
   * amount, zero fee, standard bool return, 18 decimals, no ticker collision — and clears both
   * market thresholds by a wide margin: liquidity around $181k against a $50k floor and 24h
   * volume around $185k against $100k. At twenty days it is the oldest token admitted here.
   *
   * It fails on holders alone, and that is now a measurement rather than a gap: replaying
   * every Transfer since launch leaves 798 addresses holding a positive balance, against a
   * threshold of 1,000. Close, but under it.
   *
   * This entry was first written while the count was still running, saying so. It is rewritten
   * rather than deleted because the answer came back a fail — had it come back above the
   * threshold the token would read eligible and this would have been removed outright, which
   * is what happened with ARCLIGHT. A disclosure has to describe what is actually known at the
   * time anyone reads it.
   */
  '0x3ead4e80e9e5bc0e01682d7ee74c4881b040d3ea': {
    reason: 'Admitted by the operator despite a holder count below the published floor.',
    disclose:
      'Admitted despite falling short of the holder-count threshold — 798 holders against a floor of 1,000, measured from onchain transfers. It passes every contract check and clears both the liquidity and volume thresholds comfortably.',
  },
  /*
   * ARCBAT, admitted at the operator's direction.
   *
   * Passes every contract-level check: transfer probed against live mainnet state moved the
   * full amount, zero fee, standard bool return, 18 decimals, no ticker collision. At two
   * months it is the oldest token here.
   *
   * It fails liquidity and volume, and the way it came to fail is worth recording. Its
   * verification record read ELIGIBLE until this was written, on a 2026-09-18 capture showing
   * $221k of 24h volume and $52.5k of liquidity. Refreshed against live data the same token
   * shows about $9.5k and $32.8k — volume down roughly 96% in nine days.
   *
   * Nothing was wrong with the original check; the market moved underneath it. That is the
   * same failure mode as a drifting reward band, one level up: an eligibility decision is a
   * measurement with a date on it, and this one had gone stale while still reading as a pass.
   */
  '0xbe0cad585ea2d13de2f4e36376be755c0afd8b97': {
    reason: 'Admitted by the operator despite liquidity and volume below the published floors.',
    disclose:
      'Admitted despite failing the liquidity and volume thresholds. It passes every contract check, but 24h volume is roughly a tenth of the floor — a large win may be hard to sell near the quoted price.',
  },
  /*
   * BCAT, which was admitted by the thresholds and then failed them while already in the
   * machine.
   *
   * Its record read eligible on a 2026-09-18 capture showing $336k of 24h volume and $51.6k of
   * liquidity. Refreshed on 2026-09-27 the same token shows about $1.1k and $10.8k — volume
   * down essentially to nothing in nine days. It was paying out on 5.75% of Discovery spins
   * that whole time on a pass that had stopped being true.
   *
   * Kept rather than removed, on a judgement worth writing down. The thresholds are sized for
   * a token to absorb a large win; the actual payout here is about two dollars, which is under
   * 0.02% of the remaining pool and moves the price barely at all. So a winner can still sell.
   * What they cannot rely on is that being true next week, and that is what the disclosure has
   * to say rather than the generic thin-pool wording.
   *
   * If volume keeps falling this should come out of the table, not get a longer caveat.
   */
  '0x258bbb25fb1bc34c87212f8dab34838854ef2d5d': {
    reason: 'Passed the thresholds when admitted, then fell below them while live.',
    disclose:
      'Admitted before its market thinned, and kept with that stated: 24h volume has fallen to roughly $1k with about $11k of liquidity. A typical win is small enough to sell today, but this pool is shrinking and may not support one later.',
  },
  /*
   * WAVE, admitted at the operator's direction.
   *
   * Passes every contract-level check — transfer probed against live mainnet state, full
   * amount, zero fee, standard bool return, 18 decimals, no ticker collision.
   *
   * Misses liquidity narrowly, at about $48k against a $50k floor, and volume by roughly half.
   * The liquidity figure is close enough that it will cross back and forth on ordinary market
   * movement, which is worth knowing when reading the disclosure: this is a token near the
   * line rather than far below it, unlike BCAT or ARCBAT.
   *
   * Holder count is unmeasured and recorded as zero rather than estimated.
   */
  '0xf1b72b46e2364356c1d8343590e4c0deefb19c3b': {
    reason: 'Admitted by the operator despite liquidity and volume below the published floors.',
    disclose:
      'Admitted despite falling short on liquidity and volume — about $48k and $56k against floors of $50k and $100k — and with an unmeasured holder count. It passes every contract check, and sits near the liquidity line rather than far below it.',
  },
  /*
   * oBrain, admitted at the operator's direction.
   *
   * Passes every contract-level check: transfer probed against live mainnet state moved the
   * full amount, zero fee, standard bool return, 18 decimals, no ticker collision.
   *
   * Fails liquidity and volume slightly below published floors ($47k and $50k against $50k
   * and $100k floors), with unmeasured holder count.
   */
  '0x28f986a61e078795639f239675582a12b4cf7f01': {
    reason: 'Admitted by the operator despite liquidity and volume below the published floors.',
    disclose:
      'Admitted despite falling short on liquidity and volume — about $47k and $50k against floors of $50k and $100k — and with an unmeasured holder count. It passes every contract check.',
  },
  /*
   * XAUM (Matrixdock Gold), admitted at the operator's direction.
   *
   * The strongest admission in this list on market terms, and the one that needs the most
   * said about it anyway.
   *
   * It passes every contract-level check — transfer probed against live mainnet state moved
   * the full amount, zero fee, standard bool return, 18 decimals, no ticker collision — and
   * clears liquidity by six times the floor at roughly $302k, with about 9,500 holders. It
   * fails on volume alone.
   *
   * That failure is only visible because the record was refreshed. It read ELIGIBLE on a
   * 2026-09-18 capture showing $726,900 of 24h volume; live data on 2026-09-28 shows about
   * $63,600 — down roughly 91% in ten days, through the $100k floor — while liquidity rose
   * over the same period. Admitting it on the stored pass would have published a threshold
   * claim that had quietly stopped being true, which is exactly what happened with ARCBAT.
   *
   * Two things separate this from every other reward here, and neither is a market number.
   *
   * It is a claim on gold, not a token whose value is its own. What it is worth depends on
   * Matrixdock holding the metal and honouring redemption, so a winner is exposed to that
   * issuer in a way no amount of pool depth addresses. Same shape as the Synthra sStocks.
   *
   * And the address is a UUPS proxy: 170 bytes that read the EIP-1967 implementation slot
   * and delegatecall to 0x8fac22684c16fdb25514cafc17c8643355753dd1. The clean transfer probe
   * describes that implementation, today. Whoever holds the upgrade role can replace it, and
   * transfer restrictions are ordinary for a gold RWA. This is disclosed rather than treated
   * as a contract failure because the check asks what transfers do, and today they are clean
   * — but a player should know the answer can be changed without the token address changing.
   */
  '0x178b01f61cbea1d2a5581fe1621be607835ec349': {
    reason: 'Admitted by the operator despite volume below the published floor.',
    disclose:
      'Admitted despite failing the volume threshold — 24h volume has fallen about 91% in ten days, to roughly $64k against a $100k floor, though liquidity is the deepest in the reward set at about $302k. Two things beyond the numbers: it is a claim on gold held by Matrixdock, so redemption depends on that issuer rather than on the pool; and the token is an upgradeable proxy, so the clean transfer behaviour we verified can be changed without the address changing.',
  },
  /*
   * Arcanus, admitted at the operator's direction.
   *
   * Passes every contract-level check: transfer probed against live mainnet state moved the
   * full amount, zero fee, standard bool return, 18 decimals, no ticker collision.
   *
   * Fails liquidity at about $44k against a $50k floor, volume at about $91k against $100k,
   * and holders, which is unmeasured and recorded as zero rather than estimated. Both market
   * misses are narrow — this sits near the line like WAVE rather than far below it like BCAT
   * — but it fell roughly 25% in the twenty-four hours before admission, which is the reason
   * to read those two numbers as a snapshot of a moving thing rather than a settled fact.
   *
   * On the contract shape, because XAUM in this same list is a proxy too and the difference
   * matters: Arcanus is an EIP-1167 minimal proxy, 45 bytes delegating to
   * 0x1b74922c01ddfd9c77b37d02c0a236611e8fe500. That implementation address is written into
   * the bytecode rather than read from a storage slot, so unlike an upgradeable proxy it
   * cannot be repointed. The transfer behaviour probed here is the behaviour it keeps. That
   * is a stronger guarantee than most tokens in this table offer, and it is worth saying so
   * rather than letting the word "proxy" do the opposite work.
   */
  '0x29316db42ff99f640fd4d1bb169635b6318cd430': {
    reason: 'Admitted by the operator despite liquidity and volume below the published floors.',
    disclose:
      'Admitted despite narrowly failing the liquidity and volume thresholds — about $44k and $91k against floors of $50k and $100k — and with an unmeasured holder count. It passes every contract check, and the token is a minimal proxy of the immutable kind, so the transfer behaviour verified here cannot be changed later. It fell about 25% in the day before admission, so treat the market figures as a moving snapshot.',
  },
  /*
   * Argos Bot, admitted at the operator's direction, and shown as ARGOSBOT.
   *
   * Passes every contract-level check: transfer probed against live mainnet state moved the
   * full amount, zero fee, standard bool return, 18 decimals. Like Arcanus it is an EIP-1167
   * minimal proxy — 45 bytes delegating to 0x84d4704d8a62a47c3f0a19ab4642bf77ad0e9c1f, with
   * the implementation written into the bytecode and therefore not repointable.
   *
   * It is the thinnest admission in this table by some way: about $23k of liquidity against a
   * $50k floor, which is half of what oBrain or Arcanus carry and a fifth of what the floor
   * asks. Volume misses too, at about $66k against $100k. At that depth a winner selling a
   * whole prize is a visible fraction of the pool, and the disclosure says so plainly.
   *
   * ## Why this one carries a display override
   *
   * Its ticker is ARGOS. ARGUS — a different token, different issuer, different address — is
   * already a reward on the same machine, at the ultra and jackpot tiers. One letter apart,
   * in the same drawer, at wildly different values.
   *
   * `tickerCollision` reads false for it, and that is correct rather than a bug: the checker
   * compares the strings the contracts report, and ARGOS is genuinely not ARGUS. But the
   * check exists to stop a player misreading what they won, and a one-letter difference
   * defeats a reader far more reliably than an exact duplicate does — an exact duplicate at
   * least looks like something needing attention. So the override is applied on the same
   * reasoning the exact collisions use, not because the machinery asked for it.
   *
   * Nothing about the payout changes. The machine pays an address and has never read a
   * ticker; this only governs what the interface prints.
   */
  '0xe86688530c456e099732f953ed7aa7c583026680': {
    displaySymbol: 'ARGOSBOT',
    reason: 'Admitted by the operator despite liquidity and volume below the published floors.',
    disclose:
      'Shown as ARGOSBOT because its real ticker, ARGOS, is one letter from ARGUS — an unrelated token already paid out by this machine. Admitted despite failing the liquidity and volume thresholds: about $23k and $66k against floors of $50k and $100k, making it the shallowest pool in the reward set, so a large win may be hard to sell near the quoted price. It passes every contract check, and is a minimal proxy of the immutable kind.',
  },
  /*
   * UBI, admitted at the operator's direction.
   *
   * The first admission in some time to clear both market thresholds outright: about $124k of
   * liquidity against a $50k floor and roughly $1.07m of 24h volume against $100k. On depth
   * alone it is the healthiest thing in this list.
   *
   * It fails on age, and that is the whole point of the entry. The pool opened on 2026-09-27,
   * about a day and a half before admission, against a three-day floor — and the price rose
   * roughly 210% in the twenty-four hours before it was added. Those two facts explain each
   * other: the volume that clears the threshold so comfortably is the volume of a launch
   * running hot, not of a settled market, and a three-day minimum exists precisely because a
   * day-old market has not yet shown what it does when the launch attention stops.
   *
   * The practical consequence for a player is the reward band. Bands are fixed in tokens, so
   * at a 210% daily move this one is wrong within hours in whichever direction the price
   * went, and no resize cadence catches that. It is admitted with that stated rather than
   * with the usual thin-pool wording, which would describe the opposite problem.
   *
   * Contract side it is clean: transfer probed against live mainnet state moved the full
   * amount, zero fee, standard bool return, 18 decimals, no ticker collision. The address is
   * a 44-byte Solady clone delegating to 0xd2737ccc93c511b528f50ce3745961d01512c4e8 — a
   * gas-optimised variant of the minimal proxy, and like EIP-1167 it carries the
   * implementation in its bytecode, so it cannot be repointed.
   */
  '0xfa3ffdf775cc3f6ac82cd258fb948a8a21e1749e': {
    reason: 'Admitted by the operator despite a pool younger than the published minimum.',
    disclose:
      'Admitted despite being younger than the three-day minimum — the pool opened on 2026-09-27 — and with an unmeasured holder count. Unusually for this list it clears both liquidity and volume comfortably, at about $124k and $1.07m, but that volume belongs to a launch that rose roughly 210% in its first day. Reward amounts are fixed in tokens, so at that rate of movement what this pays is likely to differ from the intended $0.95–$2.00 within hours. It passes every contract check and cannot be upgraded.',
  },
  /*
   * Mosslings, admitted at the operator's direction.
   *
   * Contract side it is clean: transfer probed against live mainnet state moved the full
   * amount, zero fee, standard bool return, 18 decimals, no ticker collision. Not a proxy —
   * 4,724 bytes of real implementation, the same size and behind the same v4 hook as oBrain,
   * so the two are almost certainly the same launchpad template.
   *
   * On market depth it is the weakest thing admitted to this table. Liquidity is about $22k
   * against a $50k floor and 24h volume about $33k against $100k — a third of the bar, where
   * ARGOS, the previous thinnest, managed two thirds. Its entire fully diluted value is
   * roughly $34k, and something close to two thirds of that sits in the pool itself.
   *
   * That last figure is the one worth stating plainly, because it is not the usual
   * thin-liquidity caveat. When the pool is most of what the token is worth, the pool is not
   * a market the prize can be sold into so much as the thing holding the price up. A win here
   * is small in absolute terms — a couple of dollars against $22k of depth, so any single
   * payout sells fine — but the disclosure should not imply the depth will still be there,
   * because there is very little behind it if it goes.
   */
  '0xafa78bc7c2e1142f4b2a225ae4aee17d6b7d7f01': {
    reason: 'Admitted by the operator despite the thinnest market in the reward set.',
    disclose:
      'Admitted despite failing the liquidity and volume thresholds by the widest margin of any reward here — about $22k and $33k against floors of $50k and $100k — and with an unmeasured holder count. Its whole fully diluted value is roughly $34k, most of it sitting in the pool itself, so the depth a win would be sold into is most of what the token is. A typical win is small enough to sell today; treat that as a statement about today. It passes every contract check.',
  },
}

/** Findings an admission may waive. Anything else keeps the token out. */
const WAIVABLE = new Set(['tickerCollision', 'meetsAge', 'researchFlag', 'meetsVolume', 'meetsHolders', 'meetsLiquidity'])

/** Contract-level checks that must all hold, admission or not. */
function contractChecksPass(t: (typeof verified.tokens)[number]): boolean {
  const c = t.checks
  return (
    c.hasContractCode &&
    c.exposesSymbol &&
    c.exposesName &&
    c.exposesDecimals &&
    c.hasNonZeroSupply &&
    c.isNotCanonicalUsdc &&
    c.transferVerified &&
    c.noTransferFee &&
    c.standardBoolReturn
  )
}

function admissible(t: (typeof verified.tokens)[number]): boolean {
  if (t.eligible) return true
  if (!ADMITTED_COLLISIONS[t.address.toLowerCase()]) return false
  if (!contractChecksPass(t)) return false
  return t.failureReasons.every((r) => WAIVABLE.has(r))
}

/**
 * Tokens paid out despite failing the published thresholds, with the disclosure text.
 *
 * Rendered on /rewards. If this list is non-empty and the page does not show it, the page is
 * making a claim that is not true.
 */
export const ADMITTED_DISCLOSURES = Object.entries(ADMITTED_COLLISIONS)
  .filter(([, v]) => Boolean(v.disclose))
  .map(([address, v]) => {
    const token = verified.tokens.find((t) => t.address.toLowerCase() === address)
    return {
      address: address as `0x${string}`,
      symbol: v.displaySymbol ?? token?.onchain.symbol ?? address.slice(0, 10),
      name: token?.onchain.name ?? 'Unknown',
      failed: token?.failureReasons ?? [],
      disclose: v.disclose!,
    }
  })

/** The label to show a player. Always use this rather than `asset.symbol`. */
export function labelFor(asset: {symbol: string; displaySymbol?: string}): string {
  return asset.displaySymbol ?? asset.symbol
}

export const REWARD_ASSETS: RewardAsset[] = verified.tokens
  .filter(admissible)
  .map(toRewardAsset)
  .filter((a): a is RewardAsset => a !== null)

/**
 * Candidates that were checked and rejected, with the reasons. Published on /rewards
 * because showing what we turned away says more about the filter than a list of winners.
 */
export const REJECTED_CANDIDATES = verified.tokens
  .filter((t) => !admissible(t))
  .map((t) => ({
    address: t.address as `0x${string}`,
    symbol: t.onchain.symbol,
    name: t.onchain.name,
    reasons: t.failureReasons,
    tickerCollision: t.tickerCollision,
    transferNote: t.transferBehaviour.note,
    researchFlag: 'researchFlag' in t ? (t.researchFlag as string) : undefined,
  }))

export const VERIFICATION_META = {
  generatedAt: verified.generatedAt,
  chainId: verified.chainId,
  verifiedAtBlock: verified.verifiedAtBlock,
  thresholds: verified.eligibilityThresholds,
  summary: verified.summary,
  sources: verified.sources,
  canonicalUsdc: verified.canonicalUsdc,
} as const

export function assetByAddress(address: string): RewardAsset | undefined {
  const lower = address.toLowerCase()
  return REWARD_ASSETS.find((a) => a.address.toLowerCase() === lower)
}

export function assetsByTier(tier: RewardTier): RewardAsset[] {
  return REWARD_ASSETS.filter((a) => a.tier === tier)
}

export const TIER_LABEL: Record<RewardTier, string> = {
  featured: 'Featured',
  verified: 'Verified by Arcade',
  discovery: 'Discovery',
  paused: 'Paused',
}

export const TIER_MEANING: Record<RewardTier, string> = {
  featured: 'Verified, and currently highlighted on a machine.',
  verified: 'Arcade confirmed the contract address, decimals and transfer behaviour.',
  discovery: 'Verified, but newer or thinner. Held to the same contract checks, higher risk.',
  paused: 'Temporarily withheld from machines. Existing rewards remain claimable.',
}
