/**
 * export-abis.ts
 *
 * Copies compiled contract ABIs out of `contracts/out` into `src/abi` as TypeScript
 * modules ending in `as const`.
 *
 * Why not import the JSON directly: a JSON import widens every `type` field to `string`,
 * which loses the literal types viem and wagmi need to infer function names, argument
 * tuples and return types. With `as const`, `useReadContract` knows that `claimable`
 * returns a `bigint` and that its args are `[Address, Address]` — so a typo in an argument
 * is a compile error rather than a runtime revert.
 *
 * Usage: pnpm export:abis   (run after `pnpm contracts:build`)
 */

import {readFileSync, writeFileSync, mkdirSync} from 'node:fs'
import {dirname, resolve} from 'node:path'
import {fileURLToPath} from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT_DIR = resolve(HERE, '../contracts/out')
const ABI_DIR = resolve(HERE, '../src/abi')

const CONTRACTS = [
  'ArcadeMachineManager',
  'CommitRevealRandomness',
  'PrizeVault',
  'RewardRegistry',
  'FeeRouter',
] as const

function camelise(name: string): string {
  return `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`
}

mkdirSync(ABI_DIR, {recursive: true})

const indexLines: string[] = [
  '// Generated by scripts/export-abis.ts. Do not edit by hand.',
  '// Regenerate with: pnpm contracts:build && pnpm export:abis',
  '',
]

for (const name of CONTRACTS) {
  const artifactPath = resolve(OUT_DIR, `${name}.sol/${name}.json`)
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8')) as {abi: unknown[]}
  const constName = camelise(name)

  const body = [
    `// Generated by scripts/export-abis.ts from contracts/src/${name}.sol. Do not edit by hand.`,
    '',
    `export const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const`,
    '',
  ].join('\n')

  writeFileSync(resolve(ABI_DIR, `${name}.ts`), body)
  indexLines.push(`export {${constName}} from './${name}'`)
  process.stdout.write(`wrote src/abi/${name}.ts (${artifact.abi.length} entries)\n`)
}

indexLines.push('')
writeFileSync(resolve(ABI_DIR, 'index.ts'), indexLines.join('\n'))
process.stdout.write('wrote src/abi/index.ts\n')
